In [1]:
import sys
if '/home/ec2-user/sagemaker-pipe-template' not in sys.path:
    sys.path.insert(0, '/home/ec2-user/sagemaker-pipe-template')
import utils, boto3, os, utils #paths
import pandas as pd
import sagemaker.core.helper.session_helper as sm_session_helper
import sagemaker.core.image_uris as sm_image_uris
import sagemaker.core.resources as sm_resources
import sagemaker.core.shapes as sm_shapes
from   sagemaker.core.training import configs as sm_train_configs
import sagemaker.core.transformer as sm_transformer
import sagemaker.train.model_trainer as sm_model_trainer
import sagemaker.core.utils.utils as sm_utils

/home/ec2-user/.local/lib/python3.9/site-packages/boto3/compat.py:89: PythonDeprecationWarning: Boto3 will no longer support Python 3.9 starting April 29, 2026. To continue receiving service updates, bug fixes, and security updates please upgrade to Python 3.10 or later. More information can be found here: https://aws.amazon.com/blogs/developer/python-support-policy-updates-for-aws-sdks-and-tools/
  warnings.warn(warning, PythonDeprecationWarning)

Existing trusted services: {'states.amazonaws.com', 'sagemaker.amazonaws.com', 'lambda.amazonaws.com', 'events.amazonaws.com'}
Trust policy already up to date for SageMakerExecutionRole-1

[06/26/26 18:09:08] INFO     Found credentials from IAM Role: ec2-1                             ]8;id=14588861;file:///home/ec2-user/.local/lib/python3.9/site-packages/botocore/credentials.py\credentials.py]8;;\:]8;id=14588862;file:///home/ec2-user/.local/lib/python3.9/site-packages/botocore/credentials.py#1171\1171]8;;\

sagemaker.config INFO - Not applying SDK defaults from location: /etc/xdg/sagemaker/config.yaml
sagemaker.config INFO - Not applying SDK defaults from location: /home/ec2-user/.config/sagemaker/config.yaml

In [39]:
# User vars
region = 'us-east-1'
model_package_group_name='abalone'
model_version=1
target_label='rings'
predict_label=target_label+'_prediction'

role = utils.get_sm_service_role_arn()
boto_session=boto3.Session(region_name=region)
sagemaker_session = sm_session_helper.Session(boto_session=boto_session)
sm_client = boto3.client('sagemaker', region_name='us-east-1')
project_dir='s3://omm-test-bucket/abalone-train'
data_dir=f'{project_dir}/data'
model_dir=f'{project_dir}/model'

train_dir=f'{data_dir}/train'
validation_dir=f'{data_dir}/validation'
test_dir=f'{data_dir}/test'
train_file=f'{data_dir}/train/train.csv'
validation_file=f'{data_dir}/validation/validation.csv'
test_file=f'{data_dir}/test/test.csv'

# For development and testing
test_X_file=test_file=f'{data_dir}/test/test_X.csv'
test_y_file=f'{data_dir}/test/test_y.csv'

[06/26/26 17:01:12] INFO     Found credentials from IAM Role: ec2-1                             ]8;id=5365160;file:///home/ec2-user/.local/lib/python3.9/site-packages/botocore/credentials.py\credentials.py]8;;\:]8;id=5365161;file:///home/ec2-user/.local/lib/python3.9/site-packages/botocore/credentials.py#1171\1171]8;;\

/home/ec2-user/.local/lib/python3.9/site-packages/boto3/compat.py:89: PythonDeprecationWarning: Boto3 will no longer support Python 3.9 starting April 29, 2026. To continue receiving service updates, bug fixes, and security updates please upgrade to Python 3.10 or later. More information can be found here: https://aws.amazon.com/blogs/developer/python-support-policy-updates-for-aws-sdks-and-tools/
  warnings.warn(warning, PythonDeprecationWarning)

In [ ]:
# DATA INGESTION
# sql=utils.Sql('user-1', 'password', 'db_1')
# abalone_df = sql.query('SELECT * FROM abalone;')
# abalone_df=abalone_df.drop(columns=['id','created_at'])

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/abalone/abalone.data"
cols = ["sex","length","diameter","height","whole_weight",
        "shucked_weight","viscera_weight","shell_weight","rings"]
abalone_df = pd.read_csv(url, header=None, names=cols)

,sex,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight,rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,7

In [ ]:
# FEATURE ENGINEERING
abalone_df = pd.get_dummies(abalone_df, columns=['sex'], drop_first=False)
abalone_df[['sex_I', 'sex_M', 'sex_F']] = abalone_df[['sex_I', 'sex_M', 'sex_F']].astype(int)
abalone_df.head()

,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight,rings,sex_F,sex_I,sex_M
0,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,15,0,0,1
1,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,7,0,0,1
2,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,9,1,0,0
3,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,10,0,0,1
4,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,7,0,1,0

In [42]:
# DATA FORMATTING
y = abalone_df['rings']
X = abalone_df.drop(columns=['rings'])

X_train, X_val, X_test, y_train, y_val, y_test = utils.train_val_test_split(X, y, train_size=0.7, val_size=0.15, random_state=42)

pd.concat([y_train, X_train], axis=1).to_csv(train_file, index=False, header=False)
pd.concat([y_val, X_val], axis=1).to_csv(validation_file, index=False, header=False)
pd.concat([y_test, X_test], axis=1).to_csv(test_file, index=False, header=False)
# pd.concat([y_val, X_val], axis=1).to_csv(baseline_file, index=False, header=True) # need header

# For development and testing
X_test.to_csv(test_X_file, index=False, header=False)
y_test.to_csv(test_y_file, index=False, header=False)

input_data_config = [
    sm_train_configs.InputData(channel_name='train', data_source=train_dir, content_type='text/csv'),
    sm_train_configs.InputData(channel_name='validation', data_source=validation_dir, content_type='text/csv')
]

In [11]:
model_trainer = sm_model_trainer.ModelTrainer(
    training_image=sm_image_uris.retrieve('xgboost', region, version='1.5-1'),
    hyperparameters={
        'objective': 'reg:squarederror',
        'num_round': '100',
        'max_depth': '5',
        'eta': '0.2',
        'subsample': '0.8',
        'eval_metric': 'rmse'
    },
    role=role,
    sagemaker_session=sagemaker_session,
    base_job_name='abalone-train-job',
    output_data_config=sm_shapes.OutputDataConfig(s3_output_path=model_dir),
    networking=sm_train_configs.Networking(
        subnets=['subnet-001be661bcef4b615', 'subnet-003ad32933ca43e74'],
        security_group_ids=['sg-00f14515abe1e47e8']
    )
)

[06/25/26 21:35:49] INFO     Ignoring unnecessary instance type: None.                            ]8;id=2330266;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/image_uris.py\image_uris.py]8;;\:]8;id=2330267;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/image_uris.py#535\535]8;;\

                    INFO     Compute not provided. Using default:                                   ]8;id=2330274;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/train/defaults.py\defaults.py]8;;\:]8;id=2330275;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/train/defaults.py#102\102]8;;\
                             instance_type='ml.m5.xlarge' instance_count=1 volume_size_in_gb=30
                             volume_kms_key_id=None keep_alive_period_in_seconds=None
                             instance_groups=None training_plan_arn=None
                             instance_placement_config=None enable_managed_spot_training=None

                    INFO     StoppingCondition not provided. Using default:                         ]8;id=2330281;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/train/defaults.py\defaults.py]8;;\:]8;id=2330282;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/train/defaults.py#128\128]8;;\
                             max_runtime_in_seconds=3600 max_wait_time_in_seconds=None
                             max_pending_time_in_seconds=None

                    INFO     Training image URI:                                               ]8;id=2330289;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/train/model_trainer.py\model_trainer.py]8;;\:]8;id=2330290;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/train/model_trainer.py#558\558]8;;\
                             683313688378.dkr.ecr.us-east-1.amazonaws.com/sagemaker-xgboost:1.
                             5-1

In [12]:
training_job = model_trainer.train(
    input_data_config=input_data_config,
    wait=True,
    logs=True
)

[06/25/26 21:35:53] INFO     SageMaker Python SDK will collect telemetry to help us better ]8;id=2330297;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/telemetry/telemetry_logging.py\telemetry_logging.py]8;;\:]8;id=2330298;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/telemetry/telemetry_logging.py#110\110]8;;\
                             understand our user's needs, diagnose issues, and deliver
                             additional features.
                             To opt out of telemetry, please disable via TelemetryOptOut
                             parameter in SDK defaults config. For more information, refer
                             to
                             https://sagemaker.readthedocs.io/en/stable/overview.html#conf
                             iguring-and-using-defaults-with-the-sagemaker-python-sdk.

sagemaker.config INFO - Not applying SDK defaults from location: /etc/xdg/sagemaker/config.yaml
sagemaker.config INFO - Not applying SDK defaults from location: /home/ec2-user/.config/sagemaker/config.yaml

                    INFO     Creating training_job resource.                                     ]8;id=2330305;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330306;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31116\31116]8;;\

                    WARNING  No region provided. Using default region.                                 ]8;id=2330313;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/utils/utils.py\utils.py]8;;\:]8;id=2330314;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/utils/utils.py#361\361]8;;\

                    INFO     Runs on sagemaker prod, region:us-east-1                                  ]8;id=2330320;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/utils/utils.py\utils.py]8;;\:]8;id=2330321;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/utils/utils.py#375\375]8;;\

                    INFO     Found credentials from IAM Role: ec2-1                             ]8;id=2330326;file:///home/ec2-user/.local/lib/python3.9/site-packages/botocore/credentials.py\credentials.py]8;;\:]8;id=2330327;file:///home/ec2-user/.local/lib/python3.9/site-packages/botocore/credentials.py#1171\1171]8;;\

[06/25/26 21:35:54] INFO     Found credentials from IAM Role: ec2-1                             ]8;id=2330332;file:///home/ec2-user/.local/lib/python3.9/site-packages/botocore/credentials.py\credentials.py]8;;\:]8;id=2330333;file:///home/ec2-user/.local/lib/python3.9/site-packages/botocore/credentials.py#1171\1171]8;;\

/home/ec2-user/.local/lib/python3.9/site-packages/rich/live.py:260: UserWarning: install "ipywidgets" for Jupyter
support
  warnings.warn('install "ipywidgets" for Jupyter support')

[06/25/26 21:38:11] INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330339;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330340;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             /miniconda3/lib/python3.8/site-packages/xgboost/compat.py:36:
                             FutureWarning: pandas.Int64Index is deprecated and will be removed
                             from pandas in a future version. Use pandas.Index with the
                             appropriate dtype instead.
                               from pandas import MultiIndex, Int64Index

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330345;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330346;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [2026-06-25 21:37:57.383 ip-172-31-97-121.ec2.internal:7 INFO
                             utils.py:28] RULE_JOB_STOP_SIGNAL_FILENAME: None

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330351;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330352;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [2026-06-25 21:37:57.404 ip-172-31-97-121.ec2.internal:7 INFO
                             profiler_config_parser.py:111] Unable to find config at
                             /opt/ml/input/config/profilerconfig.json. Profiler is disabled.

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330357;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330358;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [2026-06-25:21:37:57:INFO] Imported framework
                             sagemaker_xgboost_container.training

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330363;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330364;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [2026-06-25:21:37:57:INFO] Failed to parse hyperparameter
                             eval_metric value rmse to Json.

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330369;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330370;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             Returning the value itself

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330375;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330376;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [2026-06-25:21:37:57:INFO] Failed to parse hyperparameter objective
                             value reg:squarederror to Json.

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330381;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330382;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             Returning the value itself

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330387;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330388;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [2026-06-25:21:37:57:INFO] No GPUs detected (normal if no gpus
                             installed)

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330393;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330394;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [2026-06-25:21:37:57:INFO] Running XGBoost Sagemaker in algorithm
                             mode

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330399;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330400;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [2026-06-25:21:37:57:INFO] Determined 0 GPU(s) available on the
                             instance.

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330405;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330406;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [2026-06-25:21:37:57:INFO] Determined delimiter of CSV input is ','

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330411;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330412;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [2026-06-25:21:37:57:INFO] Determined delimiter of CSV input is ','

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330417;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330418;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [2026-06-25:21:37:57:INFO] files path: /opt/ml/input/data/train

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330423;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330424;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [2026-06-25:21:37:57:INFO] Determined delimiter of CSV input is ','

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330429;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330430;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [2026-06-25:21:37:57:INFO] files path:
                             /opt/ml/input/data/validation

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330435;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330436;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [2026-06-25:21:37:57:INFO] Determined delimiter of CSV input is ','

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330441;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330442;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [2026-06-25:21:37:57:INFO] Single node training.

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330447;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330448;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [2026-06-25:21:37:57:INFO] Train matrix has 3474 rows and 10
                             columns

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330453;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330454;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [2026-06-25:21:37:57:INFO] Validation matrix has 744 rows

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330459;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330460;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [0]#011train-rmse:8.37529#011validation-rmse:8.29357

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330465;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330466;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [1]#011train-rmse:6.85393#011validation-rmse:6.76112

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330471;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330472;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [2]#011train-rmse:5.65965#011validation-rmse:5.57577

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330477;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330478;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [3]#011train-rmse:4.74204#011validation-rmse:4.65832

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330483;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330484;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [4]#011train-rmse:4.02802#011validation-rmse:3.95836

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330489;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330490;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [5]#011train-rmse:3.48217#011validation-rmse:3.41486

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330495;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330496;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [6]#011train-rmse:3.06539#011validation-rmse:3.02706

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330501;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330502;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [7]#011train-rmse:2.76253#011validation-rmse:2.73710

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330507;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330508;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [8]#011train-rmse:2.54794#011validation-rmse:2.54107

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330513;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330514;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [9]#011train-rmse:2.37690#011validation-rmse:2.39768

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330519;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330520;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [10]#011train-rmse:2.26031#011validation-rmse:2.31277

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330525;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330526;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [11]#011train-rmse:2.18146#011validation-rmse:2.24642

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330531;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330532;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [12]#011train-rmse:2.11747#011validation-rmse:2.20169

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330537;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330538;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [13]#011train-rmse:2.07591#011validation-rmse:2.17673

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330543;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330544;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [14]#011train-rmse:2.03537#011validation-rmse:2.16287

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330549;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330550;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [15]#011train-rmse:2.00696#011validation-rmse:2.14693

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330555;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330556;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [16]#011train-rmse:1.98168#011validation-rmse:2.13264

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330561;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330562;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [17]#011train-rmse:1.96462#011validation-rmse:2.12353

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330567;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330568;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [18]#011train-rmse:1.92396#011validation-rmse:2.11182

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330573;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330574;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [19]#011train-rmse:1.91235#011validation-rmse:2.10606

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330579;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330580;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [20]#011train-rmse:1.89178#011validation-rmse:2.10310

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330585;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330586;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [21]#011train-rmse:1.87691#011validation-rmse:2.09722

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330591;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330592;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [22]#011train-rmse:1.86046#011validation-rmse:2.10378

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330597;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330598;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [23]#011train-rmse:1.84359#011validation-rmse:2.09705

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330603;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330604;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [24]#011train-rmse:1.83387#011validation-rmse:2.09829

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330609;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330610;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [25]#011train-rmse:1.82442#011validation-rmse:2.09459

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330615;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330616;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [26]#011train-rmse:1.81942#011validation-rmse:2.09190

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330621;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330622;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [27]#011train-rmse:1.80101#011validation-rmse:2.09121

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330627;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330628;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [28]#011train-rmse:1.78804#011validation-rmse:2.09818

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330633;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330634;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [29]#011train-rmse:1.78491#011validation-rmse:2.10014

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330639;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330640;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [30]#011train-rmse:1.77428#011validation-rmse:2.09669

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330645;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330646;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [31]#011train-rmse:1.76565#011validation-rmse:2.09674

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330651;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330652;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [32]#011train-rmse:1.75113#011validation-rmse:2.09456

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330657;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330658;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [33]#011train-rmse:1.73388#011validation-rmse:2.08750

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330663;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330664;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [34]#011train-rmse:1.72818#011validation-rmse:2.08568

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330669;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330670;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [35]#011train-rmse:1.70619#011validation-rmse:2.08270

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330675;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330676;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [36]#011train-rmse:1.69403#011validation-rmse:2.07900

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330681;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330682;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [37]#011train-rmse:1.67598#011validation-rmse:2.07982

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330687;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330688;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [38]#011train-rmse:1.67326#011validation-rmse:2.07705

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330693;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330694;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [39]#011train-rmse:1.67108#011validation-rmse:2.07418

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330699;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330700;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [40]#011train-rmse:1.66534#011validation-rmse:2.07134

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330705;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330706;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [41]#011train-rmse:1.64918#011validation-rmse:2.06980

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330711;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330712;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [42]#011train-rmse:1.64756#011validation-rmse:2.06847

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330717;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330718;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [43]#011train-rmse:1.64390#011validation-rmse:2.06827

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330723;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330724;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [44]#011train-rmse:1.64158#011validation-rmse:2.06869

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330729;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330730;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [45]#011train-rmse:1.63251#011validation-rmse:2.07066

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330735;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330736;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [46]#011train-rmse:1.61813#011validation-rmse:2.06458

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330741;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330742;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [47]#011train-rmse:1.61568#011validation-rmse:2.06468

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330747;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330748;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [48]#011train-rmse:1.60605#011validation-rmse:2.06605

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330753;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330754;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [49]#011train-rmse:1.59381#011validation-rmse:2.06419

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330759;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330760;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [50]#011train-rmse:1.58623#011validation-rmse:2.05810

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330765;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330766;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [51]#011train-rmse:1.57270#011validation-rmse:2.05479

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330771;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330772;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [52]#011train-rmse:1.56644#011validation-rmse:2.05718

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330777;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330778;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [53]#011train-rmse:1.55101#011validation-rmse:2.05405

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330783;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330784;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [54]#011train-rmse:1.54207#011validation-rmse:2.05460

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330789;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330790;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [55]#011train-rmse:1.53548#011validation-rmse:2.05019

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330795;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330796;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [56]#011train-rmse:1.52247#011validation-rmse:2.05014

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330801;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330802;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [57]#011train-rmse:1.51480#011validation-rmse:2.04942

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330807;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330808;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [58]#011train-rmse:1.50597#011validation-rmse:2.04572

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330813;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330814;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [59]#011train-rmse:1.49987#011validation-rmse:2.04665

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330819;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330820;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [60]#011train-rmse:1.49615#011validation-rmse:2.04636

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330825;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330826;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [61]#011train-rmse:1.48534#011validation-rmse:2.03932

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330831;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330832;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [62]#011train-rmse:1.47542#011validation-rmse:2.03920

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330837;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330838;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [63]#011train-rmse:1.46835#011validation-rmse:2.03772

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330843;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330844;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [64]#011train-rmse:1.46187#011validation-rmse:2.03395

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330849;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330850;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [65]#011train-rmse:1.45738#011validation-rmse:2.03524

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330855;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330856;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [66]#011train-rmse:1.45062#011validation-rmse:2.04077

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330861;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330862;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [67]#011train-rmse:1.44780#011validation-rmse:2.04105

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330867;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330868;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [68]#011train-rmse:1.44057#011validation-rmse:2.03985

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330873;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330874;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [69]#011train-rmse:1.43630#011validation-rmse:2.03471

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330879;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330880;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [70]#011train-rmse:1.43053#011validation-rmse:2.03439

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330885;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330886;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [71]#011train-rmse:1.41633#011validation-rmse:2.03210

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330891;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330892;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [72]#011train-rmse:1.40550#011validation-rmse:2.02960

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330897;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330898;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [73]#011train-rmse:1.40294#011validation-rmse:2.02866

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330903;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330904;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [74]#011train-rmse:1.39703#011validation-rmse:2.02654

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330909;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330910;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [75]#011train-rmse:1.39080#011validation-rmse:2.02851

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330915;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330916;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [76]#011train-rmse:1.38207#011validation-rmse:2.02721

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330921;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330922;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [77]#011train-rmse:1.37184#011validation-rmse:2.02846

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330927;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330928;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [78]#011train-rmse:1.36651#011validation-rmse:2.02741

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330933;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330934;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [79]#011train-rmse:1.35590#011validation-rmse:2.02730

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330939;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330940;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [80]#011train-rmse:1.35191#011validation-rmse:2.03401

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330945;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330946;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [81]#011train-rmse:1.34467#011validation-rmse:2.03177

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330951;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330952;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [82]#011train-rmse:1.33653#011validation-rmse:2.03084

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330957;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330958;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [83]#011train-rmse:1.33170#011validation-rmse:2.02812

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330963;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330964;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [84]#011train-rmse:1.32846#011validation-rmse:2.02926

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330969;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330970;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [85]#011train-rmse:1.32585#011validation-rmse:2.02832

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330975;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330976;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [86]#011train-rmse:1.32065#011validation-rmse:2.03004

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330981;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330982;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [87]#011train-rmse:1.31134#011validation-rmse:2.02998

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330987;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330988;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [88]#011train-rmse:1.30548#011validation-rmse:2.03359

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330993;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2330994;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [89]#011train-rmse:1.30077#011validation-rmse:2.03619

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2330999;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2331000;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [90]#011train-rmse:1.29598#011validation-rmse:2.03627

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2331005;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2331006;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [91]#011train-rmse:1.28851#011validation-rmse:2.03888

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2331011;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2331012;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [92]#011train-rmse:1.28106#011validation-rmse:2.03450

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2331017;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2331018;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [93]#011train-rmse:1.27346#011validation-rmse:2.03165

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2331023;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2331024;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [94]#011train-rmse:1.26944#011validation-rmse:2.03093

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2331029;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2331030;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [95]#011train-rmse:1.26432#011validation-rmse:2.03197

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2331035;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2331036;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [96]#011train-rmse:1.25616#011validation-rmse:2.02881

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2331041;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2331042;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [97]#011train-rmse:1.25277#011validation-rmse:2.02753

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2331047;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2331048;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [98]#011train-rmse:1.24839#011validation-rmse:2.02505

                    INFO     abalone-train-job-20260625213553/algo-1-1782423394:                 ]8;id=2331053;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2331054;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31439\31439]8;;\
                             [99]#011train-rmse:1.23891#011validation-rmse:2.02563

[06/25/26 21:38:16] INFO     Final Resource Status: Completed                                    ]8;id=2331060;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=2331061;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31442\31442]8;;\

## Resister for approval

In [ ]:
def register_new_model_version(model_package_group_name, model_data_url, image, inference_types=['ml.m5.large', 'ml.m5.xlarge'], tranform_types=['ml.m5.large', 'ml.m5.xlarge'], context_types=['text/csv'], response_mime_types=['text/csv']):
    sm_client = boto3.client('sagemaker')
    model_package_exists = False
    groups = sm_client.list_model_package_groups()
    for item in groups['ModelPackageGroupSummaryList']:
        if item['ModelPackageGroupName'] == model_package_group_name:
            print('Using existing ModelPackageGroupName')
            model_package_exists = True
            break
    if not model_package_exists:
        print('Making new ModelPackageGroupName')
        sm_client.create_model_package_group(ModelPackageGroupName=model_package_group_name)

    response = sm_client.create_model_package(
        ModelPackageGroupName='abalone',  # use group name, not ModelPackageName
        InferenceSpecification={
            'Containers': [
                {
                    'Image': image,
                    'ModelDataUrl': model_data_url
                }
            ],
            'SupportedContentTypes': context_types,
            'SupportedResponseMIMETypes': response_mime_types,
            'SupportedRealtimeInferenceInstanceTypes': inference_types,
            'SupportedTransformInstanceTypes': tranform_types
        },
        ModelApprovalStatus='PendingManualApproval'
    )

    return response['ModelPackageArn']

abalone

/home/ec2-user/.local/lib/python3.9/site-packages/boto3/compat.py:89: PythonDeprecationWarning: Boto3 will no longer support Python 3.9 starting April 29, 2026. To continue receiving service updates, bug fixes, and security updates please upgrade to Python 3.10 or later. More information can be found here: https://aws.amazon.com/blogs/developer/python-support-policy-updates-for-aws-sdks-and-tools/
  warnings.warn(warning, PythonDeprecationWarning)

In [ ]:
register_new_model_version(
    'abalone', 
    's3://omm-test-bucket/abalone-train/model/abalone-train-job-20260625213553/output/model.tar.gz', 
    sm_image_uris.retrieve('xgboost', region, version='1.5-1')
)

In [ ]:
utils.view_model_versions(boto_session)

In [68]:
import pandas as pd
import json, datetime
sm_runtime = boto3.client('sagemaker-runtime')
s3_client=boto3.client('s3')

/home/ec2-user/.local/lib/python3.9/site-packages/boto3/compat.py:89: PythonDeprecationWarning: Boto3 will no longer support Python 3.9 starting April 29, 2026. To continue receiving service updates, bug fixes, and security updates please upgrade to Python 3.10 or later. More information can be found here: https://aws.amazon.com/blogs/developer/python-support-policy-updates-for-aws-sdks-and-tools/
  warnings.warn(warning, PythonDeprecationWarning)

In [ ]:
row_nums=list(range(0,5)) # inclusive , exclusive

test_X=pd.read_csv('s3://omm-test-bucket/abalone-train/data/test/test_X.csv', header=None)

for row_num in row_nums:
    assn_id=row_num
    row=test_X.iloc[row_num]
    input = str(list(row)).replace(' ','').replace(']','').replace('[','')
    print(input)
    response = sm_runtime.invoke_endpoint(EndpointName="abalone-1-endpoint", ContentType="text/csv", Body=input, InferenceId=str(row_num))
    print(response["Body"].read().decode("utf-8"))

0.255,0.19,0.07,0.0815,0.028,0.016,0.031,0.0,1.0,0.0
{'ResponseMetadata': {'RequestId': '3dab1e19-317b-45ce-870f-7c4039389bf0', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '3dab1e19-317b-45ce-870f-7c4039389bf0', 'x-amzn-invoked-production-variant': 'AllTraffic', 'date': 'Fri, 26 Jun 2026 17:28:26 GMT', 'content-type': 'text/csv; charset=utf-8', 'content-length': '18', 'connection': 'keep-alive'}, 'RetryAttempts': 0}, 'ContentType': 'text/csv; charset=utf-8', 'InvokedProductionVariant': 'AllTraffic', 'Body': <botocore.response.StreamingBody object at 0x7f75b7935790>}
0.63,0.48,0.145,1.0115,0.4235,0.237,0.305,0.0,0.0,1.0
{'ResponseMetadata': {'RequestId': 'd81c4ad1-ebba-4e10-ae7d-4957b784b050', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'd81c4ad1-ebba-4e10-ae7d-4957b784b050', 'x-amzn-invoked-production-variant': 'AllTraffic', 'date': 'Fri, 26 Jun 2026 17:28:26 GMT', 'content-type': 'text/csv; charset=utf-8', 'content-length': '19', 'connection': 'keep-alive'}, 'RetryAttempts': 0}, 'ContentType': 'text/csv; charset=utf-8', 'InvokedProductionVariant': 'AllTraffic', 'Body': <botocore.response.StreamingBody object at 0x7f75b7935040>}
0.5,0.385,0.145,0.7615,0.246,0.195,0.204,0.0,0.0,1.0
{'ResponseMetadata': {'RequestId': '83aca346-0ba1-458f-a32c-4f7fe657983c', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '83aca346-0ba1-458f-a32c-4f7fe657983c', 'x-amzn-invoked-production-variant': 'AllTraffic', 'date': 'Fri, 26 Jun 2026 17:28:26 GMT', 'content-type': 'text/csv; charset=utf-8', 'content-length': '19', 'connection': 'keep-alive'}, 'RetryAttempts': 0}, 'ContentType': 'text/csv; charset=utf-8', 'InvokedProductionVariant': 'AllTraffic', 'Body': <botocore.response.StreamingBody object at 0x7f75b7935100>}
0.41,0.325,0.105,0.361,0.1605,0.0665,0.103,0.0,1.0,0.0
{'ResponseMetadata': {'RequestId': '9764f1b4-0dc3-4893-a277-8df1db97a526', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '9764f1b4-0dc3-4893-a277-8df1db97a526', 'x-amzn-invoked-production-variant': 'AllTraffic', 'date': 'Fri, 26 Jun 2026 17:28:26 GMT', 'content-type': 'text/csv; charset=utf-8', 'content-length': '17', 'connection': 'keep-alive'}, 'RetryAttempts': 0}, 'ContentType': 'text/csv; charset=utf-8', 'InvokedProductionVariant': 'AllTraffic', 'Body': <botocore.response.StreamingBody object at 0x7f75b79354f0>}
0.695,0.535,0.2,1.5855,0.667,0.334,0.471,1.0,0.0,0.0
{'ResponseMetadata': {'RequestId': 'e7288bbb-a50f-41b7-97ae-ea390765f178', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'e7288bbb-a50f-41b7-97ae-ea390765f178', 'x-amzn-invoked-production-variant': 'AllTraffic', 'date': 'Fri, 26 Jun 2026 17:28:26 GMT', 'content-type': 'text/csv; charset=utf-8', 'content-length': '19', 'connection': 'keep-alive'}, 'RetryAttempts': 0}, 'ContentType': 'text/csv; charset=utf-8', 'InvokedProductionVariant': 'AllTraffic', 'Body': <botocore.response.StreamingBody object at 0x7f75b7935cd0>}

In [72]:
row_nums=list(range(0,5)) # inclusive , exclusive

test_y=pd.read_csv('s3://omm-test-bucket/abalone-train/data/test/test_y.csv', header=None)
gt_bucket='omm-test-bucket'
gt_dir_key='abalone-ground-truth'

gt_data=[]
for i in range(0, len(row_nums)):
    row_num=row_nums[i]
    assn_id=str(row_num)
    # gt_val=gt_vals[i]
    gt_val=str(list(test_y.iloc[row_num])[0])
    gt_row={"groundTruthData": {"data": gt_val, "encoding": "CSV"}, "eventMetadata": {"eventId": assn_id}, "eventVersion": "0"}
    #print(gt_row)
    gt_data.append(json.dumps(gt_row).replace("'", '"'))
payload = "\n".join(gt_data)
print(payload)
# S3 key must match the data capture path structure
now = datetime.datetime.utcnow()
s3_client.put_object(
    Bucket=gt_bucket,
    Key=f"{gt_dir_key}/{now.year}/{now.month:02d}/{now.day:02d}/{now.hour:02d}{now.minute:02d}.jsonl",
    Body=payload.encode("utf-8")
)

# {"groundTruthData": {"data": "1", "encoding": "CSV"}, "eventMetadata": {"eventId": "my-row-id-101"}, "eventVersion": "0"}
# {"groundTruthData": {"data": "0", "encoding": "CSV"}, "eventMetadata": {"eventId": "my-row-id-202"}, "eventVersion": "0"}

{"groundTruthData": {"data": "5", "encoding": "CSV"}, "eventMetadata": {"eventId": "0"}, "eventVersion": "0"}
{"groundTruthData": {"data": "12", "encoding": "CSV"}, "eventMetadata": {"eventId": "1"}, "eventVersion": "0"}
{"groundTruthData": {"data": "14", "encoding": "CSV"}, "eventMetadata": {"eventId": "2"}, "eventVersion": "0"}
{"groundTruthData": {"data": "8", "encoding": "CSV"}, "eventMetadata": {"eventId": "3"}, "eventVersion": "0"}
{"groundTruthData": {"data": "11", "encoding": "CSV"}, "eventMetadata": {"eventId": "4"}, "eventVersion": "0"}

{'ResponseMetadata': {'RequestId': 'SFSC96EW33GKNZ4Z',
  'HostId': '9IznEWuToXtZNCUl/3QBWwPzfBsWtonPF8ZBxpywywZDqOQH32kuLAzDtNzVBsMUzKT17nfuuPM=',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amz-id-2': '9IznEWuToXtZNCUl/3QBWwPzfBsWtonPF8ZBxpywywZDqOQH32kuLAzDtNzVBsMUzKT17nfuuPM=',
   'x-amz-request-id': 'SFSC96EW33GKNZ4Z',
   'date': 'Fri, 26 Jun 2026 17:47:07 GMT',
   'x-amz-server-side-encryption': 'AES256',
   'etag': '"dbe6daaf88143dc085264482859b7a7c"',
   'x-amz-checksum-crc32': 'hsKyHw==',
   'x-amz-checksum-type': 'FULL_OBJECT',
   'content-length': '0',
   'server': 'AmazonS3'},
  'RetryAttempts': 0},
 'ETag': '"dbe6daaf88143dc085264482859b7a7c"',
 'ChecksumCRC32': 'hsKyHw==',
 'ChecksumType': 'FULL_OBJECT',
 'ServerSideEncryption': 'AES256'}

In [74]:
sm = boto3.client("sagemaker")

# list all schedules
schedules = sm.list_monitoring_schedules()
for s in schedules["MonitoringScheduleSummaries"]:
    print(s["MonitoringScheduleName"], s["MonitoringScheduleStatus"])

# get details on a specific schedule
response = sm.describe_monitoring_schedule(
    MonitoringScheduleName="abalone-1-endpoint-mb-mon"
)
print(response["MonitoringScheduleStatus"])   # Scheduled, Stopped, Pending
print(response["MonitoringScheduleConfig"])   # cadence, output path, etc.

abalone-1-endpoint-mb-mon Scheduled
abalone-1-endpoint-dq-mon Scheduled
abalone-1-endpoint-mq-mon Scheduled
abalone-1-endpoint-me-mon Scheduled
Scheduled
{'ScheduleConfig': {'ScheduleExpression': 'cron(0 * ? * * *)', 'DataAnalysisStartTime': '-PT2H', 'DataAnalysisEndTime': '-PT1H'}, 'MonitoringJobDefinitionName': 'abalone-1-endpoint-mb-mon-job', 'MonitoringType': 'ModelBias'}

In [75]:
executions = sm.list_monitoring_executions(
    MonitoringScheduleName="abalone-1-endpoint-mb-mon",
    SortBy="ScheduledTime",
    SortOrder="Descending",
    MaxResults=10
)

for e in executions["MonitoringExecutionSummaries"]:
    print(e["ScheduledTime"], e["MonitoringExecutionStatus"])

2026-06-26 17:00:00+00:00 Failed
2026-06-26 16:00:00+00:00 Failed